### PR TITLE
Initial data files

### PR DESCRIPTION
**Pull request by wddgit**
Initial data files for unit test

### CODE REVIEW

**Comment by Martin-Grunewald** [comment]
Data files for what unit test?

**Comment by wddgit** [comment]
please test

**Comment by missirol** [comment]
I thought it might be better to first open the CMSSW PR that needs this, and test that CMSSW PR with this PR, without having to test this one here (testing this one alone here won't really test anything, will it?).

**Comment by wddgit** [comment]
The unit test is in #41631, which I just submitted. Sorry for any confusion. I had intended to submit them both together yesterday. But I had some personal business yesterday and took half a day of vacation and had to leave work at a specific time. I thought I would get them both done before I left. I submitted one and then a minor problem not worth mentioning delayed the other... Anyway, just submitted it.

I am not sure why we run tests for these data files. I was just filling a checkbox that seemed to want to be filled... The real test is in the other PR where the unit test is run. If that unit test passes this PR should be OK.

**Comment by missirol** [comment]
+hlt

**Comment by rappoccio** [comment]
+1

**Comment by rappoccio** [comment]
merge

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
